version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env

  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

mailhog:
  image: mailhog/mailhog
  ports:
    - "8025:8025" # Interface web
    - "1025:1025" # SMTP
